// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transXviewPack.proto

package protobuf;

public final class TransXviewPackBuilder {
  private TransXviewPackBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransXviewPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransXviewPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 dataType = 1;</code>
     */
    int getDataType();

    /**
     * <code>string aid = 2;</code>
     */
    java.lang.String getAid();
    /**
     * <code>string aid = 2;</code>
     */
    com.google.protobuf.ByteString
        getAidBytes();

    /**
     * <code>string gid = 3;</code>
     */
    java.lang.String getGid();
    /**
     * <code>string gid = 3;</code>
     */
    com.google.protobuf.ByteString
        getGidBytes();

    /**
     * <code>int64 txid = 4;</code>
     */
    long getTxid();

    /**
     * <code>int64 sTime = 5;</code>
     */
    long getSTime();

    /**
     * <code>int64 eTime = 6;</code>
     */
    long getETime();

    /**
     * <code>int32 elapsed = 7;</code>
     */
    int getElapsed();

    /**
     * <code>int32 serv_h = 8;</code>
     */
    int getServH();

    /**
     * <code>int32 uagent_h = 9;</code>
     */
    int getUagentH();

    /**
     * <code>int32 qst_h = 10;</code>
     */
    int getQstH();

    /**
     * <code>int32 sql_t = 11;</code>
     */
    int getSqlT();

    /**
     * <code>int32 sql_c = 12;</code>
     */
    int getSqlC();

    /**
     * <code>int32 fetch_c = 13;</code>
     */
    int getFetchC();

    /**
     * <code>int32 cpu_t = 14;</code>
     */
    int getCpuT();

    /**
     * <code>int32 bytes = 15;</code>
     */
    int getBytes();

    /**
     * <code>string l_ip = 16;</code>
     */
    java.lang.String getLIp();
    /**
     * <code>string l_ip = 16;</code>
     */
    com.google.protobuf.ByteString
        getLIpBytes();

    /**
     * <code>string r_ip = 17;</code>
     */
    java.lang.String getRIp();
    /**
     * <code>string r_ip = 17;</code>
     */
    com.google.protobuf.ByteString
        getRIpBytes();

    /**
     * <code>string method = 18;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 18;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>int32 ref_h = 19;</code>
     */
    int getRefH();

    /**
     * <code>int32 err = 20;</code>
     */
    int getErr();

    /**
     * <code>int32 err_cls = 21;</code>
     */
    int getErrCls();

    /**
     * <code>float err_g = 22;</code>
     */
    float getErrG();

    /**
     * <code>int32 uid = 23;</code>
     */
    int getUid();
  }
  /**
   * Protobuf type {@code TransXviewPack}
   */
  public  static final class TransXviewPack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransXviewPack)
      TransXviewPackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransXviewPack.newBuilder() to construct.
    private TransXviewPack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransXviewPack() {
      dataType_ = 0;
      aid_ = "";
      gid_ = "";
      txid_ = 0L;
      sTime_ = 0L;
      eTime_ = 0L;
      elapsed_ = 0;
      servH_ = 0;
      uagentH_ = 0;
      qstH_ = 0;
      sqlT_ = 0;
      sqlC_ = 0;
      fetchC_ = 0;
      cpuT_ = 0;
      bytes_ = 0;
      lIp_ = "";
      rIp_ = "";
      method_ = "";
      refH_ = 0;
      err_ = 0;
      errCls_ = 0;
      errG_ = 0F;
      uid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransXviewPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              dataType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              aid_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              gid_ = s;
              break;
            }
            case 32: {

              txid_ = input.readInt64();
              break;
            }
            case 40: {

              sTime_ = input.readInt64();
              break;
            }
            case 48: {

              eTime_ = input.readInt64();
              break;
            }
            case 56: {

              elapsed_ = input.readInt32();
              break;
            }
            case 64: {

              servH_ = input.readInt32();
              break;
            }
            case 72: {

              uagentH_ = input.readInt32();
              break;
            }
            case 80: {

              qstH_ = input.readInt32();
              break;
            }
            case 88: {

              sqlT_ = input.readInt32();
              break;
            }
            case 96: {

              sqlC_ = input.readInt32();
              break;
            }
            case 104: {

              fetchC_ = input.readInt32();
              break;
            }
            case 112: {

              cpuT_ = input.readInt32();
              break;
            }
            case 120: {

              bytes_ = input.readInt32();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              lIp_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              rIp_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 152: {

              refH_ = input.readInt32();
              break;
            }
            case 160: {

              err_ = input.readInt32();
              break;
            }
            case 168: {

              errCls_ = input.readInt32();
              break;
            }
            case 181: {

              errG_ = input.readFloat();
              break;
            }
            case 184: {

              uid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.TransXviewPackBuilder.internal_static_TransXviewPack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.TransXviewPackBuilder.internal_static_TransXviewPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.TransXviewPackBuilder.TransXviewPack.class, protobuf.TransXviewPackBuilder.TransXviewPack.Builder.class);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>int32 dataType = 1;</code>
     */
    public int getDataType() {
      return dataType_;
    }

    public static final int AID_FIELD_NUMBER = 2;
    private volatile java.lang.Object aid_;
    /**
     * <code>string aid = 2;</code>
     */
    public java.lang.String getAid() {
      java.lang.Object ref = aid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aid_ = s;
        return s;
      }
    }
    /**
     * <code>string aid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAidBytes() {
      java.lang.Object ref = aid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GID_FIELD_NUMBER = 3;
    private volatile java.lang.Object gid_;
    /**
     * <code>string gid = 3;</code>
     */
    public java.lang.String getGid() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gid_ = s;
        return s;
      }
    }
    /**
     * <code>string gid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGidBytes() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXID_FIELD_NUMBER = 4;
    private long txid_;
    /**
     * <code>int64 txid = 4;</code>
     */
    public long getTxid() {
      return txid_;
    }

    public static final int STIME_FIELD_NUMBER = 5;
    private long sTime_;
    /**
     * <code>int64 sTime = 5;</code>
     */
    public long getSTime() {
      return sTime_;
    }

    public static final int ETIME_FIELD_NUMBER = 6;
    private long eTime_;
    /**
     * <code>int64 eTime = 6;</code>
     */
    public long getETime() {
      return eTime_;
    }

    public static final int ELAPSED_FIELD_NUMBER = 7;
    private int elapsed_;
    /**
     * <code>int32 elapsed = 7;</code>
     */
    public int getElapsed() {
      return elapsed_;
    }

    public static final int SERV_H_FIELD_NUMBER = 8;
    private int servH_;
    /**
     * <code>int32 serv_h = 8;</code>
     */
    public int getServH() {
      return servH_;
    }

    public static final int UAGENT_H_FIELD_NUMBER = 9;
    private int uagentH_;
    /**
     * <code>int32 uagent_h = 9;</code>
     */
    public int getUagentH() {
      return uagentH_;
    }

    public static final int QST_H_FIELD_NUMBER = 10;
    private int qstH_;
    /**
     * <code>int32 qst_h = 10;</code>
     */
    public int getQstH() {
      return qstH_;
    }

    public static final int SQL_T_FIELD_NUMBER = 11;
    private int sqlT_;
    /**
     * <code>int32 sql_t = 11;</code>
     */
    public int getSqlT() {
      return sqlT_;
    }

    public static final int SQL_C_FIELD_NUMBER = 12;
    private int sqlC_;
    /**
     * <code>int32 sql_c = 12;</code>
     */
    public int getSqlC() {
      return sqlC_;
    }

    public static final int FETCH_C_FIELD_NUMBER = 13;
    private int fetchC_;
    /**
     * <code>int32 fetch_c = 13;</code>
     */
    public int getFetchC() {
      return fetchC_;
    }

    public static final int CPU_T_FIELD_NUMBER = 14;
    private int cpuT_;
    /**
     * <code>int32 cpu_t = 14;</code>
     */
    public int getCpuT() {
      return cpuT_;
    }

    public static final int BYTES_FIELD_NUMBER = 15;
    private int bytes_;
    /**
     * <code>int32 bytes = 15;</code>
     */
    public int getBytes() {
      return bytes_;
    }

    public static final int L_IP_FIELD_NUMBER = 16;
    private volatile java.lang.Object lIp_;
    /**
     * <code>string l_ip = 16;</code>
     */
    public java.lang.String getLIp() {
      java.lang.Object ref = lIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lIp_ = s;
        return s;
      }
    }
    /**
     * <code>string l_ip = 16;</code>
     */
    public com.google.protobuf.ByteString
        getLIpBytes() {
      java.lang.Object ref = lIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int R_IP_FIELD_NUMBER = 17;
    private volatile java.lang.Object rIp_;
    /**
     * <code>string r_ip = 17;</code>
     */
    public java.lang.String getRIp() {
      java.lang.Object ref = rIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rIp_ = s;
        return s;
      }
    }
    /**
     * <code>string r_ip = 17;</code>
     */
    public com.google.protobuf.ByteString
        getRIpBytes() {
      java.lang.Object ref = rIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 18;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 18;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 18;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REF_H_FIELD_NUMBER = 19;
    private int refH_;
    /**
     * <code>int32 ref_h = 19;</code>
     */
    public int getRefH() {
      return refH_;
    }

    public static final int ERR_FIELD_NUMBER = 20;
    private int err_;
    /**
     * <code>int32 err = 20;</code>
     */
    public int getErr() {
      return err_;
    }

    public static final int ERR_CLS_FIELD_NUMBER = 21;
    private int errCls_;
    /**
     * <code>int32 err_cls = 21;</code>
     */
    public int getErrCls() {
      return errCls_;
    }

    public static final int ERR_G_FIELD_NUMBER = 22;
    private float errG_;
    /**
     * <code>float err_g = 22;</code>
     */
    public float getErrG() {
      return errG_;
    }

    public static final int UID_FIELD_NUMBER = 23;
    private int uid_;
    /**
     * <code>int32 uid = 23;</code>
     */
    public int getUid() {
      return uid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != 0) {
        output.writeInt32(1, dataType_);
      }
      if (!getAidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, aid_);
      }
      if (!getGidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gid_);
      }
      if (txid_ != 0L) {
        output.writeInt64(4, txid_);
      }
      if (sTime_ != 0L) {
        output.writeInt64(5, sTime_);
      }
      if (eTime_ != 0L) {
        output.writeInt64(6, eTime_);
      }
      if (elapsed_ != 0) {
        output.writeInt32(7, elapsed_);
      }
      if (servH_ != 0) {
        output.writeInt32(8, servH_);
      }
      if (uagentH_ != 0) {
        output.writeInt32(9, uagentH_);
      }
      if (qstH_ != 0) {
        output.writeInt32(10, qstH_);
      }
      if (sqlT_ != 0) {
        output.writeInt32(11, sqlT_);
      }
      if (sqlC_ != 0) {
        output.writeInt32(12, sqlC_);
      }
      if (fetchC_ != 0) {
        output.writeInt32(13, fetchC_);
      }
      if (cpuT_ != 0) {
        output.writeInt32(14, cpuT_);
      }
      if (bytes_ != 0) {
        output.writeInt32(15, bytes_);
      }
      if (!getLIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, lIp_);
      }
      if (!getRIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, rIp_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, method_);
      }
      if (refH_ != 0) {
        output.writeInt32(19, refH_);
      }
      if (err_ != 0) {
        output.writeInt32(20, err_);
      }
      if (errCls_ != 0) {
        output.writeInt32(21, errCls_);
      }
      if (errG_ != 0F) {
        output.writeFloat(22, errG_);
      }
      if (uid_ != 0) {
        output.writeInt32(23, uid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dataType_);
      }
      if (!getAidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, aid_);
      }
      if (!getGidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gid_);
      }
      if (txid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, txid_);
      }
      if (sTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sTime_);
      }
      if (eTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, eTime_);
      }
      if (elapsed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, elapsed_);
      }
      if (servH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, servH_);
      }
      if (uagentH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, uagentH_);
      }
      if (qstH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, qstH_);
      }
      if (sqlT_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, sqlT_);
      }
      if (sqlC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, sqlC_);
      }
      if (fetchC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, fetchC_);
      }
      if (cpuT_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, cpuT_);
      }
      if (bytes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, bytes_);
      }
      if (!getLIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, lIp_);
      }
      if (!getRIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, rIp_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, method_);
      }
      if (refH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, refH_);
      }
      if (err_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, err_);
      }
      if (errCls_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, errCls_);
      }
      if (errG_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(22, errG_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(23, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.TransXviewPackBuilder.TransXviewPack)) {
        return super.equals(obj);
      }
      protobuf.TransXviewPackBuilder.TransXviewPack other = (protobuf.TransXviewPackBuilder.TransXviewPack) obj;

      boolean result = true;
      result = result && (getDataType()
          == other.getDataType());
      result = result && getAid()
          .equals(other.getAid());
      result = result && getGid()
          .equals(other.getGid());
      result = result && (getTxid()
          == other.getTxid());
      result = result && (getSTime()
          == other.getSTime());
      result = result && (getETime()
          == other.getETime());
      result = result && (getElapsed()
          == other.getElapsed());
      result = result && (getServH()
          == other.getServH());
      result = result && (getUagentH()
          == other.getUagentH());
      result = result && (getQstH()
          == other.getQstH());
      result = result && (getSqlT()
          == other.getSqlT());
      result = result && (getSqlC()
          == other.getSqlC());
      result = result && (getFetchC()
          == other.getFetchC());
      result = result && (getCpuT()
          == other.getCpuT());
      result = result && (getBytes()
          == other.getBytes());
      result = result && getLIp()
          .equals(other.getLIp());
      result = result && getRIp()
          .equals(other.getRIp());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && (getRefH()
          == other.getRefH());
      result = result && (getErr()
          == other.getErr());
      result = result && (getErrCls()
          == other.getErrCls());
      result = result && (
          java.lang.Float.floatToIntBits(getErrG())
          == java.lang.Float.floatToIntBits(
              other.getErrG()));
      result = result && (getUid()
          == other.getUid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType();
      hash = (37 * hash) + AID_FIELD_NUMBER;
      hash = (53 * hash) + getAid().hashCode();
      hash = (37 * hash) + GID_FIELD_NUMBER;
      hash = (53 * hash) + getGid().hashCode();
      hash = (37 * hash) + TXID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxid());
      hash = (37 * hash) + STIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSTime());
      hash = (37 * hash) + ETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getETime());
      hash = (37 * hash) + ELAPSED_FIELD_NUMBER;
      hash = (53 * hash) + getElapsed();
      hash = (37 * hash) + SERV_H_FIELD_NUMBER;
      hash = (53 * hash) + getServH();
      hash = (37 * hash) + UAGENT_H_FIELD_NUMBER;
      hash = (53 * hash) + getUagentH();
      hash = (37 * hash) + QST_H_FIELD_NUMBER;
      hash = (53 * hash) + getQstH();
      hash = (37 * hash) + SQL_T_FIELD_NUMBER;
      hash = (53 * hash) + getSqlT();
      hash = (37 * hash) + SQL_C_FIELD_NUMBER;
      hash = (53 * hash) + getSqlC();
      hash = (37 * hash) + FETCH_C_FIELD_NUMBER;
      hash = (53 * hash) + getFetchC();
      hash = (37 * hash) + CPU_T_FIELD_NUMBER;
      hash = (53 * hash) + getCpuT();
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes();
      hash = (37 * hash) + L_IP_FIELD_NUMBER;
      hash = (53 * hash) + getLIp().hashCode();
      hash = (37 * hash) + R_IP_FIELD_NUMBER;
      hash = (53 * hash) + getRIp().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + REF_H_FIELD_NUMBER;
      hash = (53 * hash) + getRefH();
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr();
      hash = (37 * hash) + ERR_CLS_FIELD_NUMBER;
      hash = (53 * hash) + getErrCls();
      hash = (37 * hash) + ERR_G_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getErrG());
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.TransXviewPackBuilder.TransXviewPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.TransXviewPackBuilder.TransXviewPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransXviewPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransXviewPack)
        protobuf.TransXviewPackBuilder.TransXviewPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.TransXviewPackBuilder.internal_static_TransXviewPack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.TransXviewPackBuilder.internal_static_TransXviewPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.TransXviewPackBuilder.TransXviewPack.class, protobuf.TransXviewPackBuilder.TransXviewPack.Builder.class);
      }

      // Construct using kr.co.pionnet.TransXviewPackBuilder.TransXviewPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        aid_ = "";

        gid_ = "";

        txid_ = 0L;

        sTime_ = 0L;

        eTime_ = 0L;

        elapsed_ = 0;

        servH_ = 0;

        uagentH_ = 0;

        qstH_ = 0;

        sqlT_ = 0;

        sqlC_ = 0;

        fetchC_ = 0;

        cpuT_ = 0;

        bytes_ = 0;

        lIp_ = "";

        rIp_ = "";

        method_ = "";

        refH_ = 0;

        err_ = 0;

        errCls_ = 0;

        errG_ = 0F;

        uid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.TransXviewPackBuilder.internal_static_TransXviewPack_descriptor;
      }

      public protobuf.TransXviewPackBuilder.TransXviewPack getDefaultInstanceForType() {
        return protobuf.TransXviewPackBuilder.TransXviewPack.getDefaultInstance();
      }

      public protobuf.TransXviewPackBuilder.TransXviewPack build() {
        protobuf.TransXviewPackBuilder.TransXviewPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.TransXviewPackBuilder.TransXviewPack buildPartial() {
        protobuf.TransXviewPackBuilder.TransXviewPack result = new protobuf.TransXviewPackBuilder.TransXviewPack(this);
        result.dataType_ = dataType_;
        result.aid_ = aid_;
        result.gid_ = gid_;
        result.txid_ = txid_;
        result.sTime_ = sTime_;
        result.eTime_ = eTime_;
        result.elapsed_ = elapsed_;
        result.servH_ = servH_;
        result.uagentH_ = uagentH_;
        result.qstH_ = qstH_;
        result.sqlT_ = sqlT_;
        result.sqlC_ = sqlC_;
        result.fetchC_ = fetchC_;
        result.cpuT_ = cpuT_;
        result.bytes_ = bytes_;
        result.lIp_ = lIp_;
        result.rIp_ = rIp_;
        result.method_ = method_;
        result.refH_ = refH_;
        result.err_ = err_;
        result.errCls_ = errCls_;
        result.errG_ = errG_;
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.TransXviewPackBuilder.TransXviewPack) {
          return mergeFrom((protobuf.TransXviewPackBuilder.TransXviewPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.TransXviewPackBuilder.TransXviewPack other) {
        if (other == protobuf.TransXviewPackBuilder.TransXviewPack.getDefaultInstance()) return this;
        if (other.getDataType() != 0) {
          setDataType(other.getDataType());
        }
        if (!other.getAid().isEmpty()) {
          aid_ = other.aid_;
          onChanged();
        }
        if (!other.getGid().isEmpty()) {
          gid_ = other.gid_;
          onChanged();
        }
        if (other.getTxid() != 0L) {
          setTxid(other.getTxid());
        }
        if (other.getSTime() != 0L) {
          setSTime(other.getSTime());
        }
        if (other.getETime() != 0L) {
          setETime(other.getETime());
        }
        if (other.getElapsed() != 0) {
          setElapsed(other.getElapsed());
        }
        if (other.getServH() != 0) {
          setServH(other.getServH());
        }
        if (other.getUagentH() != 0) {
          setUagentH(other.getUagentH());
        }
        if (other.getQstH() != 0) {
          setQstH(other.getQstH());
        }
        if (other.getSqlT() != 0) {
          setSqlT(other.getSqlT());
        }
        if (other.getSqlC() != 0) {
          setSqlC(other.getSqlC());
        }
        if (other.getFetchC() != 0) {
          setFetchC(other.getFetchC());
        }
        if (other.getCpuT() != 0) {
          setCpuT(other.getCpuT());
        }
        if (other.getBytes() != 0) {
          setBytes(other.getBytes());
        }
        if (!other.getLIp().isEmpty()) {
          lIp_ = other.lIp_;
          onChanged();
        }
        if (!other.getRIp().isEmpty()) {
          rIp_ = other.rIp_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (other.getRefH() != 0) {
          setRefH(other.getRefH());
        }
        if (other.getErr() != 0) {
          setErr(other.getErr());
        }
        if (other.getErrCls() != 0) {
          setErrCls(other.getErrCls());
        }
        if (other.getErrG() != 0F) {
          setErrG(other.getErrG());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.TransXviewPackBuilder.TransXviewPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.TransXviewPackBuilder.TransXviewPack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dataType_ ;
      /**
       * <code>int32 dataType = 1;</code>
       */
      public int getDataType() {
        return dataType_;
      }
      /**
       * <code>int32 dataType = 1;</code>
       */
      public Builder setDataType(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataType = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object aid_ = "";
      /**
       * <code>string aid = 2;</code>
       */
      public java.lang.String getAid() {
        java.lang.Object ref = aid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          aid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string aid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAidBytes() {
        java.lang.Object ref = aid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string aid = 2;</code>
       */
      public Builder setAid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        aid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string aid = 2;</code>
       */
      public Builder clearAid() {
        
        aid_ = getDefaultInstance().getAid();
        onChanged();
        return this;
      }
      /**
       * <code>string aid = 2;</code>
       */
      public Builder setAidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        aid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gid_ = "";
      /**
       * <code>string gid = 3;</code>
       */
      public java.lang.String getGid() {
        java.lang.Object ref = gid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGidBytes() {
        java.lang.Object ref = gid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gid = 3;</code>
       */
      public Builder setGid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gid = 3;</code>
       */
      public Builder clearGid() {
        
        gid_ = getDefaultInstance().getGid();
        onChanged();
        return this;
      }
      /**
       * <code>string gid = 3;</code>
       */
      public Builder setGidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gid_ = value;
        onChanged();
        return this;
      }

      private long txid_ ;
      /**
       * <code>int64 txid = 4;</code>
       */
      public long getTxid() {
        return txid_;
      }
      /**
       * <code>int64 txid = 4;</code>
       */
      public Builder setTxid(long value) {
        
        txid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 txid = 4;</code>
       */
      public Builder clearTxid() {
        
        txid_ = 0L;
        onChanged();
        return this;
      }

      private long sTime_ ;
      /**
       * <code>int64 sTime = 5;</code>
       */
      public long getSTime() {
        return sTime_;
      }
      /**
       * <code>int64 sTime = 5;</code>
       */
      public Builder setSTime(long value) {
        
        sTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sTime = 5;</code>
       */
      public Builder clearSTime() {
        
        sTime_ = 0L;
        onChanged();
        return this;
      }

      private long eTime_ ;
      /**
       * <code>int64 eTime = 6;</code>
       */
      public long getETime() {
        return eTime_;
      }
      /**
       * <code>int64 eTime = 6;</code>
       */
      public Builder setETime(long value) {
        
        eTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 eTime = 6;</code>
       */
      public Builder clearETime() {
        
        eTime_ = 0L;
        onChanged();
        return this;
      }

      private int elapsed_ ;
      /**
       * <code>int32 elapsed = 7;</code>
       */
      public int getElapsed() {
        return elapsed_;
      }
      /**
       * <code>int32 elapsed = 7;</code>
       */
      public Builder setElapsed(int value) {
        
        elapsed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 elapsed = 7;</code>
       */
      public Builder clearElapsed() {
        
        elapsed_ = 0;
        onChanged();
        return this;
      }

      private int servH_ ;
      /**
       * <code>int32 serv_h = 8;</code>
       */
      public int getServH() {
        return servH_;
      }
      /**
       * <code>int32 serv_h = 8;</code>
       */
      public Builder setServH(int value) {
        
        servH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serv_h = 8;</code>
       */
      public Builder clearServH() {
        
        servH_ = 0;
        onChanged();
        return this;
      }

      private int uagentH_ ;
      /**
       * <code>int32 uagent_h = 9;</code>
       */
      public int getUagentH() {
        return uagentH_;
      }
      /**
       * <code>int32 uagent_h = 9;</code>
       */
      public Builder setUagentH(int value) {
        
        uagentH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uagent_h = 9;</code>
       */
      public Builder clearUagentH() {
        
        uagentH_ = 0;
        onChanged();
        return this;
      }

      private int qstH_ ;
      /**
       * <code>int32 qst_h = 10;</code>
       */
      public int getQstH() {
        return qstH_;
      }
      /**
       * <code>int32 qst_h = 10;</code>
       */
      public Builder setQstH(int value) {
        
        qstH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 qst_h = 10;</code>
       */
      public Builder clearQstH() {
        
        qstH_ = 0;
        onChanged();
        return this;
      }

      private int sqlT_ ;
      /**
       * <code>int32 sql_t = 11;</code>
       */
      public int getSqlT() {
        return sqlT_;
      }
      /**
       * <code>int32 sql_t = 11;</code>
       */
      public Builder setSqlT(int value) {
        
        sqlT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sql_t = 11;</code>
       */
      public Builder clearSqlT() {
        
        sqlT_ = 0;
        onChanged();
        return this;
      }

      private int sqlC_ ;
      /**
       * <code>int32 sql_c = 12;</code>
       */
      public int getSqlC() {
        return sqlC_;
      }
      /**
       * <code>int32 sql_c = 12;</code>
       */
      public Builder setSqlC(int value) {
        
        sqlC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sql_c = 12;</code>
       */
      public Builder clearSqlC() {
        
        sqlC_ = 0;
        onChanged();
        return this;
      }

      private int fetchC_ ;
      /**
       * <code>int32 fetch_c = 13;</code>
       */
      public int getFetchC() {
        return fetchC_;
      }
      /**
       * <code>int32 fetch_c = 13;</code>
       */
      public Builder setFetchC(int value) {
        
        fetchC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fetch_c = 13;</code>
       */
      public Builder clearFetchC() {
        
        fetchC_ = 0;
        onChanged();
        return this;
      }

      private int cpuT_ ;
      /**
       * <code>int32 cpu_t = 14;</code>
       */
      public int getCpuT() {
        return cpuT_;
      }
      /**
       * <code>int32 cpu_t = 14;</code>
       */
      public Builder setCpuT(int value) {
        
        cpuT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cpu_t = 14;</code>
       */
      public Builder clearCpuT() {
        
        cpuT_ = 0;
        onChanged();
        return this;
      }

      private int bytes_ ;
      /**
       * <code>int32 bytes = 15;</code>
       */
      public int getBytes() {
        return bytes_;
      }
      /**
       * <code>int32 bytes = 15;</code>
       */
      public Builder setBytes(int value) {
        
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bytes = 15;</code>
       */
      public Builder clearBytes() {
        
        bytes_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lIp_ = "";
      /**
       * <code>string l_ip = 16;</code>
       */
      public java.lang.String getLIp() {
        java.lang.Object ref = lIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string l_ip = 16;</code>
       */
      public com.google.protobuf.ByteString
          getLIpBytes() {
        java.lang.Object ref = lIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string l_ip = 16;</code>
       */
      public Builder setLIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string l_ip = 16;</code>
       */
      public Builder clearLIp() {
        
        lIp_ = getDefaultInstance().getLIp();
        onChanged();
        return this;
      }
      /**
       * <code>string l_ip = 16;</code>
       */
      public Builder setLIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rIp_ = "";
      /**
       * <code>string r_ip = 17;</code>
       */
      public java.lang.String getRIp() {
        java.lang.Object ref = rIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string r_ip = 17;</code>
       */
      public com.google.protobuf.ByteString
          getRIpBytes() {
        java.lang.Object ref = rIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string r_ip = 17;</code>
       */
      public Builder setRIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string r_ip = 17;</code>
       */
      public Builder clearRIp() {
        
        rIp_ = getDefaultInstance().getRIp();
        onChanged();
        return this;
      }
      /**
       * <code>string r_ip = 17;</code>
       */
      public Builder setRIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 18;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 18;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 18;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 18;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 18;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private int refH_ ;
      /**
       * <code>int32 ref_h = 19;</code>
       */
      public int getRefH() {
        return refH_;
      }
      /**
       * <code>int32 ref_h = 19;</code>
       */
      public Builder setRefH(int value) {
        
        refH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ref_h = 19;</code>
       */
      public Builder clearRefH() {
        
        refH_ = 0;
        onChanged();
        return this;
      }

      private int err_ ;
      /**
       * <code>int32 err = 20;</code>
       */
      public int getErr() {
        return err_;
      }
      /**
       * <code>int32 err = 20;</code>
       */
      public Builder setErr(int value) {
        
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 err = 20;</code>
       */
      public Builder clearErr() {
        
        err_ = 0;
        onChanged();
        return this;
      }

      private int errCls_ ;
      /**
       * <code>int32 err_cls = 21;</code>
       */
      public int getErrCls() {
        return errCls_;
      }
      /**
       * <code>int32 err_cls = 21;</code>
       */
      public Builder setErrCls(int value) {
        
        errCls_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 err_cls = 21;</code>
       */
      public Builder clearErrCls() {
        
        errCls_ = 0;
        onChanged();
        return this;
      }

      private float errG_ ;
      /**
       * <code>float err_g = 22;</code>
       */
      public float getErrG() {
        return errG_;
      }
      /**
       * <code>float err_g = 22;</code>
       */
      public Builder setErrG(float value) {
        
        errG_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float err_g = 22;</code>
       */
      public Builder clearErrG() {
        
        errG_ = 0F;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>int32 uid = 23;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>int32 uid = 23;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uid = 23;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransXviewPack)
    }

    // @@protoc_insertion_point(class_scope:TransXviewPack)
    private static final protobuf.TransXviewPackBuilder.TransXviewPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.TransXviewPackBuilder.TransXviewPack();
    }

    public static protobuf.TransXviewPackBuilder.TransXviewPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransXviewPack>
        PARSER = new com.google.protobuf.AbstractParser<TransXviewPack>() {
      public TransXviewPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransXviewPack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransXviewPack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransXviewPack> getParserForType() {
      return PARSER;
    }

    public protobuf.TransXviewPackBuilder.TransXviewPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransXviewPack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransXviewPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024transXviewPack.proto\"\354\002\n\016TransXviewPac" +
      "k\022\020\n\010dataType\030\001 \001(\005\022\013\n\003aid\030\002 \001(\t\022\013\n\003gid\030" +
      "\003 \001(\t\022\014\n\004txid\030\004 \001(\003\022\r\n\005sTime\030\005 \001(\003\022\r\n\005eT" +
      "ime\030\006 \001(\003\022\017\n\007elapsed\030\007 \001(\005\022\016\n\006serv_h\030\010 \001" +
      "(\005\022\020\n\010uagent_h\030\t \001(\005\022\r\n\005qst_h\030\n \001(\005\022\r\n\005s" +
      "ql_t\030\013 \001(\005\022\r\n\005sql_c\030\014 \001(\005\022\017\n\007fetch_c\030\r \001" +
      "(\005\022\r\n\005cpu_t\030\016 \001(\005\022\r\n\005bytes\030\017 \001(\005\022\014\n\004l_ip" +
      "\030\020 \001(\t\022\014\n\004r_ip\030\021 \001(\t\022\016\n\006method\030\022 \001(\t\022\r\n\005" +
      "ref_h\030\023 \001(\005\022\013\n\003err\030\024 \001(\005\022\017\n\007err_cls\030\025 \001(" +
      "\005\022\r\n\005err_g\030\026 \001(\002\022\013\n\003uid\030\027 \001(\005B(\n\rkr.co.p" +
      "ionnetB\025TransXviewPackBuilderH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransXviewPack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransXviewPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransXviewPack_descriptor,
        new java.lang.String[] { "DataType", "Aid", "Gid", "Txid", "STime", "ETime", "Elapsed", "ServH", "UagentH", "QstH", "SqlT", "SqlC", "FetchC", "CpuT", "Bytes", "LIp", "RIp", "Method", "RefH", "Err", "ErrCls", "ErrG", "Uid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
